{
 "title": "Container Metrics",
 "description": "Dashboard for Docker containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container(s)",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"},name)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory usage per container",
   "type": "timeseries",
   "description": "Preferred way to view memory usage, Portainer also uses this method compared to showing RSS memory usage.\n\n**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS memory per container",
   "type": "timeseries",
   "description": "**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory cached per container",
   "type": "timeseries",
   "description": "**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap memory cached per container",
   "type": "timeseries",
   "description": "**NOTE**: This graph joins all containers with the same name together sometimes causing visible memory usage spikes (on the graph) when recreating containers. Toggle the `Split Containers` query in the panel editing UI to change this behavior.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}) by(name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Memory limit per container",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "description": "Remaining memory for containers with memory limits set",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    (container_spec_memory_limit_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"} != 0) -\n    container_memory_usage_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"}\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used memory of the limit",
   "type": "table",
   "description": "Used memory for containers with memory limits set",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - (\n    ((container_spec_memory_limit_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"} != 0)  - \n     container_memory_usage_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"}) * 100 / \n     container_spec_memory_limit_bytes{name=~\"$container\",name=~\".+\",instance=~\"$instance\",image!=\"\"})\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Sent network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"$instance\",job=~\"$job\",name=~\"$container\",name=~\".+\",image!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Last created",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{job=~\"$job\", instance=~\"$instance\", image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$instance\",job=~\"$job\",image!=\"\"})"
    }
   ]
  }
 ]
}