apiVersion: 1

policies:
  - orgId: 1
    # The default, catch-all receiver for everything (Warning, Critical, etc.).
    receiver: ms-teams-contact-point

    # Grouping ensures we don't get X messages for X similar alerts.
    group_by: ["grafana_folder", "alertname"]

    # Wait to see if more alerts come in for the same group before sending.
    group_wait: 30s

    # If a new alert is added to the group, wait before sending an update.
    group_interval: 5m

    # Resend the notification if it is still firing.
    repeat_interval: 4h
